Update some scripts to be more POSIX-friendly

diff --git a/ebook-extract b/ebook-extract
--- a/ebook-extract
+++ b/ebook-extract
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Extract an epub or a mobi ebook into FILENAME.extracted/, or into the specified new target directory.
@@ -11,14 +10,16 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
 outputDir="."
 mobiExtractorPath="/usr/local/bin/mobi_unpack.py"
 filename=""
+
+require "${mobiExtractorPath}" "See: http://wiki.mobileread.com/wiki/KindleUnpack"
 
 if [ $# -eq 0 ]; then
 	usage
@@ -28,36 +29,36 @@ for i in "$@"
 do
 case $i in
 	-d=*|--destination=*)
-		outputDir=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		outputDir=$(echo "${i}" | sed 's/[-a-zA-Z0-9]*=//')
 	;;
 	*)
-		filename="$i"
+		filename="${i}"
 	;;
 esac
 done
 
-if [ "$outputDir" = "." ]; then
-	outputDir="$outputDir/$1.extracted/"
+if [ "${outputDir}" = "." ]; then
+	outputDir="${outputDir}/$1.extracted/"
 fi
 
-if [ -d "$outputDir" ]; then
-	die "$outputDir already exists."
+if [ -d "${outputDir}" ]; then
+	die "${outputDir} already exists."
 fi
 
-if [ "$filename" = "" ]; then
+if [ "${filename}" = "" ]; then
 	usage
 fi
 
 #Handle .mobi files
-if file "$filename" | grep -i ": Mobipocket E-book" &> /dev/null; then
-	require "$mobiExtractorPath" "See: http://wiki.mobileread.com/wiki/KindleUnpack"
-	mkdir "$outputDir"
-	"$mobiExtractorPath" "$filename" "$outputDir" > /dev/null
+if file "${filename}" | grep -i ": Mobipocket E-book" > /dev/null 2>&1; then
+	require "${mobiExtractorPath}" "See: http://wiki.mobileread.com/wiki/KindleUnpack"
+	mkdir "${outputDir}"
+	"${mobiExtractorPath}" "${filename}" "${outputDir}" > /dev/null
 
 #Handle .epub files
-elif file "$filename" | grep -i ": EPUB ebook data" &> /dev/null; then
-	mkdir "$outputDir"
-	unzip "$filename" -d "$outputDir" > /dev/null
+elif file "${filename}" | grep -i ": EPUB ebook data" > /dev/null 2>&1; then
+	mkdir "${outputDir}"
+	unzip "${filename}" -d "${outputDir}" > /dev/null
 else
 	die "Unrecognized ebook file."
 fi
diff --git a/encrypted-folder b/encrypted-folder
--- a/encrypted-folder
+++ b/encrypted-folder
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Create, mount, and unmount encfs volumes.
@@ -15,17 +14,17 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
-decryptedRoot="$HOME"
+decryptedRoot="${HOME}"
 
 require "encfs" "Try: apt-get install encfs"
 require "pip" "Try: apt-get install python-pip"
 #We require the keyring python library
-pip list | grep "keyring" &> /dev/null
+pip freeze 2> /dev/null | grep "keyring" > /dev/null 2>&1
 if [ $? -ne 0 ]; then
 	die "Python keyring library is not installed.  Try: pip install keyring"
 fi
@@ -37,13 +36,16 @@ fi
 if [ $# -eq 1 ]; then
 	if [ "$1" = "set-password" ]; then
 		#This currently doesn't seem to work with 12.04 LTS.
+		die "Currently broken.  Sorry!"
 		me=$(whoami)
-		echo "New password:"
-		read -s pw
-		python -c "import keyring;print keyring.set_password('""encrypted-folder""', '""$me""', '""$pw""')" &> /dev/null
+		printf "New password:"
+		stty -echo
+		read pw
+		stty echo
+		python -c "import keyring;print keyring.set_password('""encrypted-folder""', '""${me}""', '""${pw}""')" > /dev/null 2>&1
 	elif [ "$1" = "--unmount" -o "$1" = "-u" ]; then
-		find "$decryptedRoot" -maxdepth 1 -type d -name '*.decrypted' -exec fusermount -u {} \;
-		find "$decryptedRoot" -maxdepth 1 -type d -name '*.decrypted' -exec rmdir {} \;
+		find "${decryptedRoot}" -maxdepth 1 -type d -name '*.decrypted' -exec fusermount -u {} \;
+		find "${decryptedRoot}" -maxdepth 1 -type d -name '*.decrypted' -exec rmdir {} \;
 	else
 		die "Invalid options.  Use -h for help."
 	fi
@@ -52,36 +54,36 @@ fi
 if [ $# -eq 2 ]; then
 	if [ "$1" = "--mount" -o "$1" = "-m" ]; then
 		encryptedFolderPath=$(readlink -f "$2")
-		encryptedFolder=$(basename "$encryptedFolderPath")
-		decryptedFolderPath="$decryptedRoot"/"$encryptedFolder".decrypted
+		encryptedFolder=$(basename "${encryptedFolderPath}")
+		decryptedFolderPath="${decryptedRoot}"/"${encryptedFolder}".decrypted
 		me=$(whoami)
 		
-		if [ -d "$decryptedFolderPath" ] ; then
+		if [ -d "${decryptedFolderPath}" ] ; then
 			die "Directory already mounted."
 		fi
 		
-		mkdir -p "$encryptedFolderPath" #in case we're creating a new volume
-		mkdir -p "$decryptedFolderPath"
+		mkdir -p "${encryptedFolderPath}" #in case we're creating a new volume
+		mkdir -p "${decryptedFolderPath}"
 		
 		#Do we have a stored password?  If so, use it
-		pw=$(python -c "import keyring;print keyring.get_password('encrypted-folder', '$me')")
+		pw=$(python -c "import keyring;print keyring.get_password('encrypted-folder', '${me}')")
 		
-		if [ "$pw" = "None" ]; then
-			encfs "$encryptedFolderPath" "$decryptedFolderPath"
+		if [ "${pw}" = "None" ]; then
+			encfs "${encryptedFolderPath}" "${decryptedFolderPath}"
 		else
-			echo -n "$pw" | encfs -S "$encryptedFolderPath" "$decryptedFolderPath"
+			printf "${pw}" | encfs -S "${encryptedFolderPath}" "${decryptedFolderPath}"
 		fi
 		
 		if [ "$?" -eq 0 ]; then
-			echo "Mounted at $decryptedFolderPath/"
+			printf "Mounted at %s/\n" "${decryptedFolderPath}"
 		else
-			rmdir "$decryptedFolderPath"
+			rmdir "${decryptedFolderPath}"
 		fi
 	elif [ "$1" = "--unmount" -o "$1" = "-u" ]; then
 		decryptedFolderPath=$(readlink -f "$2")
-		if [ -d "$decryptedFolderPath" ] ; then
-			fusermount -u "$decryptedFolderPath"
-			rmdir "$decryptedFolderPath"
+		if [ -d "${decryptedFolderPath}" ] ; then
+			fusermount -u "${decryptedFolderPath}"
+			rmdir "${decryptedFolderPath}"
 		else
 			die "Not a directory."
 		fi
@@ -89,4 +91,3 @@ if [ $# -eq 2 ]; then
 		die "Invalid options.  Use -h for help."
 	fi
 fi
-
diff --git a/geolocate-ip b/geolocate-ip
--- a/geolocate-ip
+++ b/geolocate-ip
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Use the ipinfodb.com API to geolocate a list of IP addresses from arguments, a file, or standard input.  By default the API key for ipinfodb.com is read from ~/.config/geolocate-ip/ipinfodb.com-api-key
@@ -22,8 +21,8 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
@@ -34,11 +33,11 @@ apiKey=""
 pause=false
 ips=()
 
-function isValidIp(){
-    local  ip=$1
-    local  stat=1
+isValidIp(){
+    local ip="$1"
+    local stat=1
 
-    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+    if [[ "${ip}" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
         OIFS=$IFS
         IFS='.'
         ip=($ip)
@@ -50,7 +49,7 @@ function isValidIp(){
     return $stat
 }
 
-function geolocateIp(){
+geolocateIp(){
     	local ip=$1
 	if isValidIp $ip; then
 		if [ $countryOnly = true ]; then
@@ -113,18 +112,18 @@ else
 	#We have input from arguments
 	for ip in $@
 	do
-		ips=("${ips[@]}" "$ip")
+		ips=("${ips[@]}" "${ip}")
 	done
 fi
 
 if [ ${#ips[@]} -gt 1 ]; then
-	pause=true
+	pause="true"
 fi
 
 for ip in "${ips[@]}"
 do
-	geolocateIp $ip
-	if [ $pause = true ]; then
+	geolocateIp "${ip}"
+	if [ "${pause}" = "true" ]; then
 		sleep 1
 	fi
 done
diff --git a/kindle-sync b/kindle-sync
--- a/kindle-sync
+++ b/kindle-sync
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Compile and sync ebooks in ~/documents/ebooks/ to an attached Kindle device, then eject it.  Epub files are compiled to mobi files and cover thumbnails are transferred automatically.
@@ -18,8 +17,8 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
@@ -35,32 +34,32 @@ convertFile(){
 	tempPath="/tmp" #No trailing slash please!
 	filename=$(basename "$1" ".epub")
 	fileLocation=$(dirname "$1")
-	mobiPath="$fileLocation"/"$filename.compiled.mobi"
+	mobiPath="${fileLocation}"/"${filename}.compiled.mobi"
 	tempMobiPath="/tmp/mobi" #No trailing slash please!
 	
-	echo "Compiling $mobiPath ..."
+	echo "Compiling ${mobiPath} ..."
 
 	#First convert epub to mobi
-	ebook-convert "$1" "$mobiPath" &> /dev/null
+	ebook-convert "$1" "${mobiPath}" > /dev/null 2>&1
 	
 	#Store the md5 sum of the epub
-	echo "$md5" > "$fileLocation/last-epub-md5"
+	echo "${md5}" > "${fileLocation}/last-epub-md5"
 
 	#Extract the mobi file to get the asin
-	rm -rf "$tempMobiPath" &> /dev/null
-	ebook-extract -d="$tempMobiPath" "$mobiPath" 
+	rm -rf "${tempMobiPath}" > /dev/null 2>&1
+	ebook-extract -d="${tempMobiPath}" "${mobiPath}" 
 
 	#Get the ASIN
-	asin=$(grep -o -E '<meta name="ASIN" content="(.*)"' "$tempMobiPath"/mobi7/*.opf | sed -E 's/.*content="(.*)"/\1/')
+	asin=$(grep -o -E '<meta name="ASIN" content="(.*)"' "${tempMobiPath}"/mobi7/*.opf | sed -E 's/.*content="(.*)"/\1/')
 
 	#Generate the thumbnail
-	rm "$fileLocation"/thumbnail_* &> /dev/null
+	rm "${fileLocation}"/thumbnail_* > /dev/null 2>&1
 	
 	#Get the name of the cover image
-	coverPath=$(grep -o -E '<item id="cover_img" media-type=".*?" href="(.*)"' "$tempMobiPath"/mobi7/*.opf | sed -E 's/.*href\="(.*)"/\1/')
+	coverPath=$(grep -o -E '<item id="cover_img" media-type=".*?" href="(.*)"' "${tempMobiPath}"/mobi7/*.opf | sed -E 's/.*href\="(.*)"/\1/')
 
 	#Resize the cover
-	convert "$tempMobiPath/mobi7/$coverPath" -resize 216x330 "$fileLocation/thumbnail_"$asin"_EBOK_portrait.jpg" &> /dev/null
+	convert "${tempMobiPath}/mobi7/${coverPath}" -resize 216x330 "${fileLocation}/thumbnail_${asin}_EBOK_portrait.jpg" > /dev/null 2>&1
 }
 
 dryRun=false
@@ -68,87 +67,87 @@ compileOnly=false
 
 if [ $# -eq 1 ]; then
 	if [ "$1" = "--dry-run" -o "$1" = "-d" ]; then
-		dryRun=true
+		dryRun="true"
 	fi
 	if [ "$1" = "--compile-only" -o "$1" = "-c" ]; then
-		compileOnly=true
+		compileOnly="true"
 	fi
 fi
 
-if [ $compileOnly != true ]; then
-	if [ ! -d "$kindleRoot" ]; then
+if [ "${compileOnly}" != "true" ]; then
+	if [ ! -d "${kindleRoot}" ]; then
 		die "Kindle not mounted."
 	fi
 fi
 
-find "$ebooksRoot" -name "*.epub" | while read filePath;
+find "${ebooksRoot}" -name "*.epub" | while read filePath;
 do
 	#Ignore epub files that end in .original.epub
-	if [[ "$filePath" == *.original.epub ]]; then
+	if [ "${filePath}" = *.original.epub ]; then
 		continue
 	fi
 	
 	#Ignore epub files that end in .wip.epub
-	if [[ "$filePath" == *.wip.epub ]]; then
+	if [ "${filePath}" = *.wip.epub ]; then
 		continue
 	fi
 	
 	#Do we have a cached copy of the mobi file?
-	fileName=$(basename "$filePath" ".epub")
-	fileLocation=$(dirname "$filePath")
+	fileName=$(basename "${filePath}" ".epub")
+	fileLocation=$(dirname "${filePath}")
 	
-	if ls "$fileLocation/last-epub-md5" &> /dev/null ; then
+	if ls "${fileLocation}/last-epub-md5" > /dev/null 2>&1 ; then
 		#Mobi exists
 		
-		currentMd5=$(md5sum "$filePath" | awk '{ print $1 }')
-		cachedMd5=$(cat "$fileLocation/last-epub-md5")
+		currentMd5=$(md5sum "${filePath}" | awk '{ print $1 }')
+		cachedMd5=$(cat "${fileLocation}/last-epub-md5")
 		
 		#Have we made changes?
-		if [ "$currentMd5" != "$cachedMd5" ]; then
-			convertFile "$filePath"
+		if [ "${currentMd5}" != "${cachedMd5}" ]; then
+			convertFile "${filePath}"
 		fi
 	else
 		#Mobi does not exist, create it for the first time
-		convertFile "$filePath"
+		convertFile "${filePath}"
 	fi
 done
 
 #Rsync thumbnails to the device
-rm -rf "/tmp/images-sync/" &> /dev/null
-mkdir -p "/tmp/images-sync/" &> /dev/null
+rm -rf "/tmp/images-sync/" > /dev/null 2>&1
+mkdir -p "/tmp/images-sync/" > /dev/null 2>&1
 
 #Don't sync for a dry run
-if [ $compileOnly != true -a $dryRun != true ]; then
-	find "$ebooksRoot" -name "*.jpg" | while read filePath;
+if [ "${compileOnly}" != "true" -a "${dryRun}" != "true" ]; then
+	find "${ebooksRoot}" -name "*.jpg" | while read filePath;
 	do
-		cp "$filePath" "/tmp/images-sync/"
+		cp "${filePath}" "/tmp/images-sync/"
 	done
 	
-	rsync -rlcvz --itemize-changes --include="*.jpg" --delete  "/tmp/images-sync/" "$kindleRoot/system/thumbnails" &> /dev/null
+	rsync -rlcvz --itemize-changes --include="*.jpg" --delete  "/tmp/images-sync/" "${kindleRoot}/system/thumbnails" > /dev/null 2>&1
 fi
 
 #Rsync books to the device
 #Ignore .sdr folders and .original.mobi files
-rm -rf "/tmp/mobi-sync" &> /dev/null
+rm -rf "/tmp/mobi-sync" > /dev/null 2>&1
 
-if [ $compileOnly != true ]; then
-	if [ ! -d "$kindleRoot/documents/ebooks" ]; then
-		mkdir -p "$kindleRoot/documents/ebooks"
+if [ "${compileOnly}" != "true" ]; then
+	if [ ! -d "${kindleRoot}/documents/ebooks" ]; then
+		mkdir -p "${kindleRoot}/documents/ebooks"
 	fi
 fi
 
-if [ $dryRun = true ]; then
+if [ "${dryRun}" = "true" ]; then
 	echo Starting rsync dry run ...
-	rsync -rlcvz --dry-run --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete  "$ebooksRoot" "$kindleRoot/documents/ebooks"
-elif [ $compileOnly != true ]; then
+	rsync -rlcvz --dry-run --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete  "${ebooksRoot}" "${kindleRoot}/documents/ebooks"
+elif [ "${compileOnly}" != "true" ]; then
 	#Empty my clippings
-	echo "" > "$kindleRoot/documents/My Clippings.txt"
-	rsync -rlcvz --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete "$ebooksRoot" "$kindleRoot/documents/ebooks"
+	echo "" > "${kindleRoot}/documents/My Clippings.txt"
+	rsync -rlcvz --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete "${ebooksRoot}" "${kindleRoot}/documents/ebooks"
 fi
 
-if [ $dryRun != true -a $compileOnly != true ] ; then
+if [ "${dryRun}" != "true" -a "${compileOnly}" != "true" ] ; then
 	echo "Ejecting Kindle ..."
-	sudo eject "$kindleRoot"
+	sudo eject "${kindleRoot}"
 	echo "Done."
 fi
 
diff --git a/nook-sync b/nook-sync
--- a/nook-sync
+++ b/nook-sync
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Sync ebooks in ~/documents/ebooks/ to an attached Nook device, then eject it.
@@ -13,31 +12,30 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
-ebooksRoot="$HOME/documents/ebooks/" #Trailing slash required
-nookRoot=/media/NOOK
+ebooksRoot="${HOME}/documents/ebooks/" #Trailing slash required
+nookRoot="/media/NOOK"
 
 require "rsync" "Try: apt-get install rsync"
 
-if [ ! -d "$nookRoot" ]; then
+if [ ! -d "${nookRoot}" ]; then
 	die "Nook not mounted."
 fi
 
 if [ $# -eq 1 ]; then
-	echo Starting rsync dry run ...
-	rsync -rlcvz --itemize-changes --dry-run --include="*/" --exclude="*.original.epub" --exclude="*.pdf" --include="*.epub"  --exclude="*" --delete  "$ebooksRoot" "$nookRoot/My Files/Books/"
+	echo "Starting rsync dry run ..."
+	rsync -rlcvz --itemize-changes --dry-run --include="*/" --exclude="*.original.epub" --exclude="*.pdf" --include="*.epub"  --exclude="*" --delete  "${ebooksRoot}" "${nookRoot}/My Files/Books/"
 else
-	echo Starting rsync ...
-	rsync -rlcvz --itemize-changes --include="*/" --exclude="*.original.epub" --exclude="*.pdf" --include="*.epub" --exclude="*" --delete  "$ebooksRoot" "$nookRoot/My Files/Books/"
+	echo "Starting rsync ..."
+	rsync -rlcvz --itemize-changes --include="*/" --exclude="*.original.epub" --exclude="*.pdf" --include="*.epub" --exclude="*" --delete  "${ebooksRoot}" "${nookRoot}/My Files/Books/"
 
 	if [ $? -eq 0 ] ; then
 		echo "Ejecting Nook ..."
-		sudo eject "$nookRoot"
+		sudo eject "${nookRoot}"
 		echo "Done."
 	fi
 fi;
-
diff --git a/ogg-cover-art b/ogg-cover-art
--- a/ogg-cover-art
+++ b/ogg-cover-art
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Add cover art to an OGG file.
@@ -15,8 +14,8 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
@@ -32,13 +31,13 @@ imagePath=""
 if [ $# -eq 1 ]; then
 	outputFile="$1"
 	dirName=$(dirname "$1")
-	imagePath="$dirName/cover.jpg"
-	if [ ! -f "$imagePath" ]; then
-		imagePath="$dirName/cover.jpeg"
-		if [ ! -f "$imagePath" ]; then
-			imagePath="$dirName/cover.png"
-			if [ ! -f "$imagePath" ]; then
-				die "Couldn't find a cover image in $dirName."
+	imagePath="${dirName}/cover.jpg"
+	if [ ! -f "${imagePath}" ]; then
+		imagePath="${dirName}/cover.jpeg"
+		if [ ! -f "${imagePath}" ]; then
+			imagePath="${dirName}/cover.png"
+			if [ ! -f "${imagePath}" ]; then
+				die "Couldn't find a cover image in ${dirName}."
 			fi
 		fi
 	fi
@@ -49,23 +48,23 @@ if [ $# -eq 2 ]; then
 	imagePath="$1"
 fi
 
-if [ ! -f "$outputFile" ]; then
+if [ ! -f "${outputFile}" ]; then
 	die "Couldn't find ogg file."
 fi
 
-if [ ! -f "$imagePath" ]; then
+if [ ! -f "${imagePath}" ]; then
 	die "Couldn't find cover image."
 fi
 
-imageMimeType=$(mimetype -b "$imagePath")
+imageMimeType=$(mimetype -b "${imagePath}")
 
-if [ "$imageMimeType" != "image/jpeg" -a "$imageMimeType" != "image/png" ]; then
+if [ "${imageMimeType}" != "image/jpeg" -a "${imageMimeType}" != "image/png" ]; then
 	die "Cover image isn't a jpg or png image."
 fi
 
-oggMimeType=$(mimetype -b "$outputFile")
+oggMimeType=$(mimetype -b "${outputFile}")
 
-if [ "$oggMimeType" != "audio/x-vorbis+ogg" ]; then
+if [ "${oggMimeType}" != "audio/x-vorbis+ogg" ]; then
 	die "Input file isn't an ogg file."
 fi
 
diff --git a/pw b/pw
--- a/pw
+++ b/pw
@@ -1,16 +1,15 @@
 #!/bin/bash
 
-passwordFilePath="$HOME/.passwords" #No trailing slash
+passwordFilePath="${HOME}/.passwords" #No trailing slash
 clipboardTime=30
-configFile="$HOME/.config/pw/private-key"
-syncFile="$HOME/.config/pw/sync-credentials"
+configFile="${HOME}/.config/pw/private-key"
+syncFile="${HOME}/.config/pw/sync-credentials"
 recipient=""
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
-	Create, edit, and view gpg-encrypted passwords stored in the $passwordFilePath/ folder.
+	Create, edit, and view gpg-encrypted passwords stored in the ${passwordFilePath}/ folder.
 	
 	By default, pw encrypts passwords symmetrically using a passphrase.  To encrypt with a GPG key instead, create the file ~/.config/pw/private-key containing the email address of the private key to use.  The private key must be on your keychain.
 
@@ -19,24 +18,24 @@ USAGE
 		List stored domains.
 
 	pw -g,--generate [DOMAIN]
-		Generate and print a new strong password to stdout and copy it to the clipboard for $clipboardTime seconds.  If invoked with a domain name, additionally prompt for a login, then store the login and generated password in the password store.
+		Generate and print a new strong password to stdout and copy it to the clipboard for ${clipboardTime} seconds.  If invoked with a domain name, additionally prompt for a login, then store the login and generated password in the password store.
 	
 	pw -a,--add DOMAIN
 		Prompt for a login and password for a domain, then store those credentials in the password store.
 
 	pw -s,--show DOMAIN
-		Show stored credentials for the specified domain and copy the password to the clipboard for $clipboardTime seconds.
+		Show stored credentials for the specified domain and copy the password to the clipboard for ${clipboardTime} seconds.
 
 	pw -e,--edit DOMAIN
 		Edit the information stored under that domain using a temporary file stored in a RAMFS mount.  Requires sudo privileges.
 	
 	pw -c,--sync [USER@HOST:DESTINATION]
-		Sync the $passwordFilePath/ folder to the USER@HOST:DESTINATION specified in ~/.config/pw/sync-credentials or as an argument.
+		Sync the ${passwordFilePath}/ folder to the USER@HOST:DESTINATION specified in ~/.config/pw/sync-credentials or as an argument.
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
@@ -51,170 +50,178 @@ require "rsync" "Try: apt-get install rsync"
 generatePassword(){
 	password=$(sort -R /usr/share/dict/words | head -n 100 | grep -i '^[a-z]*$' | head -n 4 | sed ':a;N;$!ba;s/\n/ /g')
 		
-	randomPos=$[ ( $RANDOM % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( $RANDOM % ${#specialCharacters} )  +  1 ]-1:1}
-	password=$(echo "$password" | sed "s/\(.\)/\1$randomChar/$randomPos")
+	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
 	
-	randomPos=$[ ( $RANDOM % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( $RANDOM % ${#specialCharacters} )  +  1 ]-1:1}
-	password=$(echo "$password" | sed "s/\(.\)/\1$randomChar/$randomPos")
+	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
 	
-	randomPos=$[ ( $RANDOM % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( $RANDOM % ${#specialCharacters} )  +  1 ]-1:1}
-	password=$(echo "$password" | sed "s/\(.\)/\1$randomChar/$randomPos")
+	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
 	
-	randomPos=$[ ( $RANDOM % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( $RANDOM % ${#specialCharacters} )  +  1 ]-1:1}
-	password=$(echo "$password" | sed "s/\(.\)/\1$randomChar/$randomPos")
+	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
 	
-	echo -n "$password"
+	printf "%s" "${password}"
 }
 
 syncPasswords(){
 	#Remove any trailing slashes, then add one
 	target=${1%/}
-	target="$target/"
-	rsync -acz --progress --itemize-changes --partial -e ssh "$passwordFilePath/" "$target"
+	target="${target}/"
+	rsync -acz --progress --itemize-changes --partial -e ssh "${passwordFilePath}/" "${target}"
 }
 
-if [ -f "$configFile" ]; then
-	recipient=$(cat "$configFile")
+if [ -f "${configFile}" ]; then
+	recipient=$(cat "${configFile}")
 fi
 
 if [ $# -eq 0 ]; then	
-	tree "$passwordFilePath/" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
+	tree "${passwordFilePath}/" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
 fi
 
 if [ $# -eq 1 ]; then
 	if [ "$1" = "-g" -o "$1" = "--generate" ]; then
-		password=$(generatePassword)
+		password="$(generatePassword)"
 		
-		echo $password
-		echo -n "$password" | xclip -selection clipboard
-		sleep "$clipboardTime" && echo -n "" | xclip -selection clipboard &
+		echo ${password}
+		printf "%s" "${password}" | xclip -selection clipboard
+		sleep "${clipboardTime}" && printf "" | xclip -selection clipboard &
 	elif [ "$1" = "-l" -o "$1" = "--list" ]; then
-		tree "$passwordFilePath" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
+		tree "${passwordFilePath}" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
 	elif [ "$1" = "-c" -o "$1" = "--sync" ]; then
-		if [ -f "$syncFile" ]; then
-			destination=$(cat "$syncFile")
-			syncPasswords "$destination"
+		if [ -f "${syncFile}" ]; then
+			destination=$(cat "${syncFile}")
+			syncPasswords "${destination}"
 		else
-			die "$syncFile does not exist."
+			die "${syncFile} does not exist."
 		fi
 	fi
 fi
 
 if [ $# -eq 2 ]; then
 	if [ "$1" = "-g" -o "$1" = "--generate" ]; then
-		if [ -f "$passwordFilePath/$2.gpg" ]; then	
-			read -p "This domain already exists.  Overwrite? (y/n) " yn
-			case $yn in
+		if [ -f "${passwordFilePath}/$2.gpg" ]; then
+			printf "This domain already exists.  Overwrite? (y/n) "
+			read yn
+			case "${yn}" in
 				[Yy]* ) :;;
 				[Nn]* ) exit;;
 				* ) exit;;
 			esac
 		fi
-
-		read -p "Enter your login for this domain: " login
-
-		password=$(generatePassword)
 		
-		if [ "$recipient" = "" ]; then
-			echo -e "login: $login\npass: $password" | gpg --symmetric --armor --batch --yes --output "$passwordFilePath/$2.gpg"
+		printf "Enter your login for this domain: "
+		read login
+
+		password="$(generatePassword)"
+		
+		if [ "${recipient}" = "" ]; then
+			printf "login: ${login}\npass: ${password}" | gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg"
 		else
-			echo -e "login: $login\npass: $password" | gpg --encrypt --armor --batch --yes --recipient "$recipient" --output "$passwordFilePath/$2.gpg"
+			printf "login: ${login}\npass: ${password}" | gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg"
 		fi
 	
-		echo $password
-		echo -n "$password" | xclip -selection clipboard
-		sleep "$clipboardTime" && echo -n "" | xclip -selection clipboard &
+		printf "%s" "${password}"
+		printf "%s" "${password}" | xclip -selection clipboard
+		sleep "${clipboardTime}" && printf "" | xclip -selection clipboard &
 	elif [ "$1" = "-a" -o "$1" = "--add" ]; then
-		if [ -f "$passwordFilePath/$2.gpg" ]; then	
-			read -p "This domain already exists.  Overwrite? (y/n) " yn
-			case $yn in
+		if [ -f "${passwordFilePath}/$2.gpg" ]; then	
+			printf "This domain already exists.  Overwrite? (y/n) "
+			read yn
+			case "${yn}" in
 				[Yy]* ) :;;
 				[Nn]* ) exit;;
 				* ) exit;;
 			esac
 		fi
 
-		read -p "Enter your login for this domain: " login
+		printf "Enter your login for this domain: "
+		read login
 		
-		#Note: The newlines here are required without indentation for things to appear nicely.
-		read -s -p "Enter your password for this domain:
-" password
-		read -s -p "Repeat your password for this domain:
-" passwordConfirm
+		printf "Enter your password for this domain: "
+		stty -echo
+		read password
+		stty echo
+		printf "\nRepeat your password for this domain: "
+		stty -echo
+		read passwordConfirm
+		stty echo
+		printf "\n"
 		
-		if [ "$password" != "$passwordConfirm" ]; then
+		if [ "${password}" != "${passwordConfirm}" ]; then
 			die "Passwords don't match."
 		fi
 		
-		if [ "$recipient" = "" ]; then
-			echo -e "login: $login\npass: $password" | gpg --symmetric --armor --batch --yes --output "$passwordFilePath/$2.gpg"
+		if [ "${recipient}" = "" ]; then
+			printf "login: ${login}\npass: ${password}" | gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg"
 		else
-			echo -e "login: $login\npass: $password" | gpg --encrypt --armor --batch --yes --recipient "$recipient" --output "$passwordFilePath/$2.gpg"
+			printf "login: ${login}\npass: ${password}" | gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg"
 		fi
 	elif [ "$1" = "-s" -o "$1" = "--show" ]; then
-		if [ -f "$passwordFilePath/$2.gpg" ]; then
-			text=$(gpg --use-agent --decrypt --no-tty "$passwordFilePath/$2.gpg" 2> /dev/null)
+		if [ -f "${passwordFilePath}/$2.gpg" ]; then
+			text=$(gpg --use-agent --decrypt --no-tty "${passwordFilePath}/$2.gpg" 2> /dev/null)
 			
 			if [ $? -ne 0 ]; then
 				die "Invalid password."
 			fi
 			
-			echo -e "$text"
+			printf "%s\n" "${text}"
 			
-			echo -e "$text" | grep -i -E "^pass(word)?\:\s.*" &> /dev/null
+			printf "%s" "${text}" | grep -i -E "^pass(word)?\:\s.*" > /dev/null 2>&1
 			if [ $? -eq 0 ]; then
-				password=$(echo -e -n "$text" | grep -i -E "^pass(word)?\:\s.*" | sed -r "s/^pass(word)?\:\s//")
-				if [ "$password" != "" ]; then
-					echo -n "$password" | xclip -selection clipboard
-					sleep "$clipboardTime" && echo -n "" | xclip -selection clipboard &
+				password=$(printf "%s" "${text}" | grep -i -E "^pass(word)?\:\s.*" | sed -r "s/^pass(word)?\:\s//")
+				if [ "${password}" != "" ]; then
+					printf "%s" "${password}" | xclip -selection clipboard
+					sleep "${clipboardTime}" && printf "" | xclip -selection clipboard &
 				fi
 			fi
 		else
 			die "File not found."
 		fi
 	elif [ "$1" = "-e" -o "$1" = "--edit" ]; then
-		if [ -f "$passwordFilePath/$2.gpg" ]; then
-			mkdir -p "$tempMountPoint"
+		if [ -f "${passwordFilePath}/$2.gpg" ]; then
+			mkdir -p "${tempMountPoint}"
 			
-			sudo umount "$tempMountPoint" &> /dev/null
+			sudo umount "${tempMountPoint}" > /dev/null 2>&1
 			
-			sudo mount -t ramfs -o size=20m ramfs "$tempMountPoint"
+			sudo mount -t ramfs -o size=20m ramfs "${tempMountPoint}"
 			
 			if [ $? -ne 0 ]; then
 				die "Couldn't create temporary mount.  Do you have sudo privileges?"
 			fi
 			
-			sudo chown $(whoami) "$tempMountPoint"
+			sudo chown $(whoami) "${tempMountPoint}"
 			
-			filename=$(basename "$2")
-			filePath="$tempMountPoint/$filename"
+			filename="$(basename "$2")"
+			filePath="${tempMountPoint}/${filename}"
 			
-			gpg --use-agent --decrypt --no-tty --output "$filePath" "$passwordFilePath/$2.gpg" 2> /dev/null
+			gpg --use-agent --decrypt --no-tty --output "${filePath}" "${passwordFilePath}/$2.gpg" 2> /dev/null
 			
 			if [ $? -ne 0 ]; then
-				sudo umount "$tempMountPoint"
+				sudo umount "${tempMountPoint}"
 				die "Invalid password."
 			fi
 			
-			if [ "$EDITOR" = "" ]; then
-				vi "$filePath"
+			if [ "${EDITOR}" = "" ]; then
+				vi "${filePath}"
 			else
-				$EDITOR "$filePath"
+				"${EDITOR}" "${filePath}"
 			fi
 			
-			if [ "$recipient" = "" ]; then
-				gpg --symmetric --armor --batch --yes --output "$passwordFilePath/$2.gpg" "$filePath"
+			if [ "${recipient}" = "" ]; then
+				gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg" "${filePath}"
 			else
-				gpg --encrypt --armor --batch --yes --recipient "$recipient" --output "$passwordFilePath/$2.gpg" "$filePath"
+				gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg" "${filePath}"
 			fi
 			
-			rm "$filePath"
+			rm "${filePath}"
 			
-			sudo umount "$tempMountPoint"
+			sudo umount "${tempMountPoint}"
 		else
 			die "File not found."
 		fi
diff --git a/screen-toggle b/screen-toggle
--- a/screen-toggle
+++ b/screen-toggle
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Toggle the laptop display on or off.
@@ -11,26 +10,47 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
 require "xdotool" "Try: apt-get install xdotool"
 
-screenOffLockFile=/tmp/screen-toggle-lock
+screenOffLockFile="/tmp/screen-toggle-lock"
 
-if [ -f $screenOffLockFile ];
+if [ -f ${screenOffLockFile} ];
 then
-	rm $screenOffLockFile
-	notify-send "Screen on" -i /usr/share/icons/gnome/48x48/devices/computer.png
+	rm ${screenOffLockFile}
+	
+	#Enable mice and trackpads
+	xinput list | grep -E --only-matching "id=[0-9]+\s*\[slave\s+pointer" | grep -E --only-matching "[0-9]+" | while read -r deviceId; do
+	echo a
+		xinput --set-prop "${deviceId}" "Device Enabled" 1
+	done
+	
+	#Turn on the screen
 	xset dpms force on
+	
+	#Simulate mouse movement to ensure the screen stays on
+	#xdotool mousemove 0 0 mousemove restore
+	
+	#Show a notice
+	notify-send "Screen on" -i /usr/share/icons/gnome/48x48/devices/computer.png
 else
-	touch $screenOffLockFile
-	sleep .5
+	touch "${screenOffLockFile}"
+
+	#Disable mice and trackpads
+	xinput list | grep -E --only-matching "id=[0-9]+\s*\[slave\s+pointer" | grep -E --only-matching "[0-9]+" | while read -r deviceId; do
+	echo a
+		xinput --set-prop "${deviceId}" "Device Enabled" 0
+	done
+	
+	xset dpms force off
+	
 	while true 
 	do
-		if [ -f $screenOffLockFile ];
+		if [ -f "${screenOffLockFile}" ];
 		then
 			xset dpms force off
 		else
@@ -41,5 +61,5 @@ else
 	xset dpms force on
 	
 	#Simulate mouse movement to ensure the screen stays on
-	xdotool mousemove 0 0 mousemove restore
+	#xdotool mousemove 0 0 mousemove restore
 fi
diff --git a/set-brightness b/set-brightness
--- a/set-brightness
+++ b/set-brightness
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
-brightness=0
+brightness="0"
 
 usage(){
 	echo -n
@@ -9,23 +9,26 @@ DESCRIPTION
 	Set the laptop screen brightness level.
 	
 USAGE
-	set-brightness [0-15]
-		The brightness level defaults to $brightness.
+	set-brightness INTEGER
 EOF
 	exit
 }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
-
 
 if [ $# -ne 0 ]; then
 	brightness="$1"
 fi
 
-if [[ "$brightness" =~ ^[0-9]+$ ]]; then
-	echo -e "$brightness" | sudo tee /sys/class/backlight/acpi_video0/brightness > /dev/null
-else
-	die "Expecting a number."
+case ${brightness#[-+]} in
+	*[!0-9]* ) die "Expecting an integer." ;;
+esac
+
+maxBrightness="$(cat /sys/class/backlight/acpi_video0/max_brightness)"
+
+if [ "${brightness}" -gt "${maxBrightness}" ]; then
+	die "Maximum brightness is ${maxBrightness}."
 fi
 
-
+printf "${brightness}" | sudo tee /sys/class/backlight/acpi_video0/brightness > /dev/null
diff --git a/socks-tunnel b/socks-tunnel
--- a/socks-tunnel
+++ b/socks-tunnel
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Control a transparent system-level or browser-level SOCKS tunnel through a remote proxy.
@@ -20,16 +19,16 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
-localPort=12345
-socksPort=11080 #The default socks port is 1080, but we use an alternate in case other services want to use that port
+localPort="12345"
+socksPort="11080" #The default socks port is 1080, but we use an alternate in case other services want to use that port
 remoteConnection=""
-tempFilePath=/tmp/socks-tunnel
-configFilePath="$HOME/.config/socks-tunnel/host"
+tempFilePath="/tmp/socks-tunnel"
+configFilePath="${HOME}/.config/socks-tunnel/host"
 command=""
 type="tun"
 
@@ -42,7 +41,7 @@ require "badvpn-tun2socks" "Try:\napt-add-repository ppa:ambrop7/badvpn\napt-get
 
 for i in "$@"
 do
-case $i in
+case "${i}" in
 	-s|--start)
 		command="start"
 	;;
@@ -56,7 +55,7 @@ case $i in
 		type="browser"
 	;;
 	-h=*|--host=*)
-		remoteConnection=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		remoteConnection="$(echo "${i}" | sed 's/[-a-zA-Z0-9]*=//')"
 	;;
 esac
 done
@@ -66,8 +65,8 @@ error(){
 }
 
 checkIfRunning(){
-	if [ -f "$tempFilePath" ]; then
-		if [ -s "$tempFilePath" ]; then
+	if [ -f "${tempFilePath}" ]; then
+		if [ -s "${tempFilePath}" ]; then
 			die "Network-layer-level SOCKS tunnel open."
 		else
 			die "Browser-level SOCKS tunnel open."
@@ -78,16 +77,16 @@ checkIfRunning(){
 isFirefoxRunning(){
 	#Get the PID for the Firefox process
 	ffpid=$(ps ux | awk '/firefox/ && !/awk/ && !/socks/ {print $2}')
-	[ -n "$ffpid" ]
+	[ -n "${ffpid}" ]
 }
 
 startTun(){
 	#Save our detected settings
-	remoteUser=`echo "$remoteConnection" | cut -d"@" -f1-1`
-	remoteHost=`echo "$remoteConnection" | cut -d"@" -f2-2`
+	remoteUser=`echo "${remoteConnection}" | cut -d"@" -f1-1`
+	remoteHost=`echo "${remoteConnection}" | cut -d"@" -f2-2`
 	gatewayIp=$(/sbin/ip route | awk '/default/ { print $3 }')
-	remoteIp=$(host -t a "$remoteHost" | awk '{print $4}')
-	echo -e "$gatewayIp\n$remoteIp" > "$tempFilePath"
+	remoteIp=$(host -t a "${remoteHost}" | awk '{print $4}')
+	printf "${gatewayIp}\n${remoteIp}" > "${tempFilePath}"
 
 	#Create the tun0 device
 	sudo openvpn --mktun --dev tun0 > /dev/null
@@ -96,51 +95,51 @@ startTun(){
 	sudo ifconfig tun0 10.0.0.1 netmask 255.255.255.0 > /dev/null
 	
 	#Enable the tun2socks program
-	badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:$socksPort > /dev/null & 
+	badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:${socksPort} > /dev/null & 
 	disown %badvpn
 	
 	#Open our socks proxy
-	ssh -D localhost:$socksPort -N -f $remoteConnection
+	ssh -D localhost:${socksPort} -N -f ${remoteConnection}
 
 	#Connect to tun2socks instead of our default gateway (router)
-	sudo route add "$remoteIp" gw "$gatewayIp" metric 5 
+	sudo route add "${remoteIp}" gw "${gatewayIp}" metric 5 
 	sudo route add default gw 10.0.0.2 metric 6 #connect to tun2socks instead of our default gateway (router)
-	sudo route del default gw "$gatewayIp" metric 0 #delete our default gateway connection
+	sudo route del default gw "${gatewayIp}" metric 0 #delete our default gateway connection
 }
 
 stopTun(){
 	#Restore our detected settings
-	gatewayIp=$(awk "NR==1" "$tempFilePath")
-	remoteIp=$(awk "NR==2" "$tempFilePath")
+	gatewayIp=$(awk "NR==1" "${tempFilePath}")
+	remoteIp=$(awk "NR==2" "${tempFilePath}")
 	
 	#Get the pid for the ssh and badvpn processes
 	sshPid=$(ps ux | awk '/ssh -D/ && !/awk/ {print $2}')
 	badvpnPid=$(ps ux | awk '/badvpn/ && !/awk/ {print $2}')
 
 	#Remove our socks routes and restore our default gateway route
-	sudo route del "$remoteIp" gw "$gatewayIp" metric 5 &> /dev/null
-	sudo route del default gw 10.0.0.2 metric 6 &> /dev/null
-	sudo route add default gw "$gatewayIp" metric 0 &> /dev/null
+	sudo route del "${remoteIp}" gw "${gatewayIp}" metric 5 > /dev/null 2>&1
+	sudo route del default gw 10.0.0.2 metric 6 > /dev/null 2>&1
+	sudo route add default gw "${gatewayIp}" metric 0 > /dev/null 2>&1
 	
 	#Kill the ssh and badvpn processes
-	kill -HUP $sshPid &> /dev/null
-	kill -HUP $badvpnPid &> /dev/null
+	kill -HUP ${sshPid} > /dev/null 2>&1
+	kill -HUP ${badvpnPid} > /dev/null 2>&1
 	
 	#Remove the tun0 device
 	sudo openvpn --rmtun --dev tun0 > /dev/null
 	
-	rm "$tempFilePath"
+	rm "${tempFilePath}"
 }
 
 startFirefox(){
-	ssh -D $localPort -N -f $remoteConnection
+	ssh -D ${localPort} -N -f ${remoteConnection}
 
 	if [ $? -ne 0 ]; then
 		die "Could not establish SSH connection."
 	else
-		touch "$tempFilePath"
+		touch "${tempFilePath}"
 		
-		echo -e "user_pref(\"network.proxy.socks\", \"localhost\");\nuser_pref(\"network.proxy.socks_port\", $localPort);\nuser_pref(\"network.proxy.socks_version\", 5);\nuser_pref(\"network.proxy.type\", 1);" > $(echo $(find ~/.mozilla/firefox -name '*.default')/user.js)
+		printf "user_pref(\"network.proxy.socks\", \"localhost\");\nuser_pref(\"network.proxy.socks_port\", ${localPort});\nuser_pref(\"network.proxy.socks_version\", 5);\nuser_pref(\"network.proxy.type\", 1);" > $(echo $(find ~/.mozilla/firefox -name '*.default')/user.js)
 
 		if isFirefoxRunning; then
 			echo "Restart Firefox to apply proxy changes."
@@ -153,17 +152,17 @@ stopFirefox(){
 		die "Firefox is still running."
 	fi
 	
-	rm "$tempFilePath"
+	rm "${tempFilePath}"
 	
 	echo "user_pref(\"network.proxy.type\", 5);" > $(echo $(find ~/.mozilla/firefox -name '*.default')/user.js)
 
 	#Get the PID for the SSH process
 	pid=$(ps ux | awk '/ssh -D/ && !/awk/ {print $2}')
 
-	if [ -z $pid ]; then
+	if [ -z "${pid}" ]; then
 		die "Could not find SSH process ID."
 	else
-		kill -HUP $pid &> /dev/null
+		kill -HUP "${pid}" > /dev/null 2>&1
 		
 		if isFirefoxRunning; then
 			echo "Restart Firefox to apply proxy changes."
@@ -171,38 +170,38 @@ stopFirefox(){
 	fi
 }
 
-if [ "$command" = "start" ]; then
+if [ "${command}" = "start" ]; then
 	checkIfRunning
 	
 	#If we haven't specified a host on the command line, try to find it in our config directory
-	if [ "$remoteConnection" = "" ]; then
-		if [ -f "$configFilePath" ]; then
-			remoteConnection=$(cat "$configFilePath")
+	if [ "${remoteConnection}" = "" ]; then
+		if [ -f "${configFilePath}" ]; then
+			remoteConnection=$(cat "${configFilePath}")
 		fi
 	fi
 	
-	if [ "$remoteConnection" = "" ]; then
+	if [ "${remoteConnection}" = "" ]; then
 		error
 	fi
 	
-	if [ "$type" = "tun" ]; then
+	if [ "${type}" = "tun" ]; then
 		startTun
-	elif [ "$type" = "browser" ]; then
+	elif [ "${type}" = "browser" ]; then
 		startFirefox
 	else
 		error
 	fi
-elif [ "$command" = "stop" ]; then
-	if [ -f "$tempFilePath" ]; then
-		if [ -s "$tempFilePath" ]; then
+elif [ "${command}" = "stop" ]; then
+	if [ -f "${tempFilePath}" ]; then
+		if [ -s "${tempFilePath}" ]; then
 			stopTun
 		else
 			stopFirefox
 		fi
 	fi
-elif [ "$command" = "status" ]; then
-	if [ -f "$tempFilePath" ]; then
-		if [ -s "$tempFilePath" ]; then
+elif [ "${command}" = "status" ]; then
+	if [ -f "${tempFilePath}" ]; then
+		if [ -s "${tempFilePath}" ]; then
 			echo "Socks proxy running using tun."
 		else
 			echo "Socks proxy running using SSH/Firefox."
diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Manage the ~/.todo todo file.
@@ -30,8 +29,8 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
diff --git a/update-dns-record b/update-dns-record
--- a/update-dns-record
+++ b/update-dns-record
@@ -1,7 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 
 usage(){
-	echo -n
 	fmt <<EOF
 DESCRIPTION
 	Check if the IP address of this host matches the DNS records of a remote host.  If it doesn't match, update the DNS records using the Linode API.
@@ -11,8 +10,8 @@ USAGE
 EOF
 	exit
 }
-die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
+die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
+require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
 if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
 #End boilerplate
 
@@ -25,31 +24,31 @@ resourceId=""
 
 for i in "$@"
 do
-case $i in
+case "${i}" in
 	-h=*|--host=*)
-		dynamicHost=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		dynamicHost="$(echo ${i} | sed 's/[-a-zA-Z0-9]*=//')"
 	;;
 	-k=*|--api-key=*)
-		linodeApiKey=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		linodeApiKey="$(echo ${i} | sed 's/[-a-zA-Z0-9]*=//')"
 	;;
 	-d=*|--domain-id=*)
-		domainId=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		domainId="$(echo ${i} | sed 's/[-a-zA-Z0-9]*=//')"
 	;;
 	-r=*|--resource-id=*)
-		resourceId=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		resourceId="$(echo ${i} | sed 's/[-a-zA-Z0-9]*=//')"
 	;;
 esac
 done
 
-if [ "$dynamicHost" = "" -o "$linodeApiKey" = "" -o "$domainId" = "" -o "$resourceId" = "" ]; then
+if [ "${dynamicHost}" = "" -o "${linodeApiKey}" = "" -o "${domainId}" = "" -o "${resourceId}" = "" ]; then
 	usage
 fi
 
 #look up the existing dns entry
-dnsIp=$(dig +short "$dynamicHost")
+dnsIp=$(dig +short "${dynamicHost}")
 
-if [ "$dnsIp" = "" ]; then
-	die "Could not resolve $dynamicHost while looking up DNS records."
+if [ "${dnsIp}" = "" ]; then
+	die "Could not resolve ${dynamicHost} while looking up DNS records."
 fi
 
 #look up our external ip
@@ -59,8 +58,8 @@ if [ $? -ne 0 ]; then
 	die "Could not resolve ifconfig.me while looking up local IP."
 fi
 
-if [ "$dnsIp" != "$localIp" ]; then
-	curl "https://api.linode.com/?api_key=$linodeApiKey&api_action=domain.resource.update&domainid=$domainId&resourceid=$resourceId&target=$localIp" &> /dev/null
+if [ "${dnsIp}" != "${localIp}" ]; then
+	curl "https://api.linode.com/?api_key=${linodeApiKey}&api_action=domain.resource.update&domainid=${domainId}&resourceid=${resourceId}&target=${localIp}" > /dev/null 2>&1
 	
 	if [ $? -ne 0 ]; then
 		die "Could not connect to Linode API."
