Some shellcheck fixes

diff --git a/encrypted-folder b/encrypted-folder
--- a/encrypted-folder
+++ b/encrypted-folder
@@ -8,24 +8,24 @@ DESCRIPTION
 USAGE
 	encrypted-folder -m,--mount DIRECTORY
 		Decrypt and mount DIRECTORY into ~/DIRECTORY.decrypted/.  If DIRECTORY doesn't exist or isn't an encfs volume, create a new encfs volume.
-	
+
 	encrypted-folder -u,--unmount [DIRECTORY]
 		Unmount all mounted encfs directories matching "~/*.decrypted", or a single specified directory.
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 decryptedRoot="${HOME}"
 
 require "encfs" "Try: apt-get install encfs"
 require "pip" "Try: apt-get install python-pip"
-#We require the keyring python library
-pip freeze 2> /dev/null | grep "keyring" > /dev/null 2>&1
-if [ $? -ne 0 ]; then
+# We require the keyring python library
+
+if ! pip freeze 2> /dev/null | grep "keyring" > /dev/null 2>&1; then
 	die "Python keyring library is not installed.  Try: pip install keyring"
 fi
 
@@ -35,7 +35,7 @@ fi
 
 if [ $# -eq 1 ]; then
 	if [ "$1" = "set-password" ]; then
-		#This currently doesn't seem to work with 12.04 LTS.
+		# This currently doesn't seem to work with 12.04 LTS.
 		die "Currently broken.  Sorry!"
 		me=$(whoami)
 		printf "New password:"
@@ -43,7 +43,7 @@ if [ $# -eq 1 ]; then
 		read pw
 		stty echo
 		python -c "import keyring;print keyring.set_password('""encrypted-folder""', '""${me}""', '""${pw}""')" > /dev/null 2>&1
-	elif [ "$1" = "--unmount" -o "$1" = "-u" ]; then
+	elif [ "$1" = "--unmount" ] || [ "$1" = "-u" ]; then
 		find "${decryptedRoot}" -maxdepth 1 -type d -name '*.decrypted' -exec fusermount -u {} \;
 		find "${decryptedRoot}" -maxdepth 1 -type d -name '*.decrypted' -exec rmdir {} \;
 	else
@@ -52,34 +52,34 @@ if [ $# -eq 1 ]; then
 fi
 
 if [ $# -eq 2 ]; then
-	if [ "$1" = "--mount" -o "$1" = "-m" ]; then
+	if [ "$1" = "--mount" ] || [ "$1" = "-m" ]; then
 		encryptedFolderPath=$(readlink -f "$2")
 		encryptedFolder=$(basename "${encryptedFolderPath}")
 		decryptedFolderPath="${decryptedRoot}"/"${encryptedFolder}".decrypted
 		me=$(whoami)
-		
+
 		if [ -d "${decryptedFolderPath}" ] ; then
 			die "Directory already mounted."
 		fi
-		
-		mkdir -p "${encryptedFolderPath}" #in case we're creating a new volume
+
+		mkdir -p "${encryptedFolderPath}" # in case we're creating a new volume
 		mkdir -p "${decryptedFolderPath}"
-		
-		#Do we have a stored password?  If so, use it
+
+		# Do we have a stored password?  If so, use it
 		pw=$(python -c "import keyring;print keyring.get_password('encrypted-folder', '${me}')")
-		
+
 		if [ "${pw}" = "None" ]; then
 			encfs "${encryptedFolderPath}" "${decryptedFolderPath}"
 		else
-			printf "${pw}" | encfs -S "${encryptedFolderPath}" "${decryptedFolderPath}"
+			printf "%s" "${pw}" | encfs -S "${encryptedFolderPath}" "${decryptedFolderPath}"
 		fi
-		
+
 		if [ "$?" -eq 0 ]; then
 			printf "Mounted at %s/\n" "${decryptedFolderPath}"
 		else
 			rmdir "${decryptedFolderPath}"
 		fi
-	elif [ "$1" = "--unmount" -o "$1" = "-u" ]; then
+	elif [ "$1" = "--unmount" ] || [ "$1" = "-u" ]; then
 		decryptedFolderPath=$(readlink -f "$2")
 		if [ -d "${decryptedFolderPath}" ] ; then
 			fusermount -u "${decryptedFolderPath}"
diff --git a/geolocate-ip b/geolocate-ip
--- a/geolocate-ip
+++ b/geolocate-ip
@@ -7,24 +7,24 @@ DESCRIPTION
 
 USAGE
 	geolocate-ip [-f,--file=FILENAME] [-c,--country-only] [-k,--api-key=APIKEY] [IPADDRESS[ IPADDRESS ...]]
-	
-		-f,--file		Read the IPs from the specified 
-					file, one per line.  Ignore any 
-					IP addresses that are passed as 
+
+		-f,--file		Read the IPs from the specified
+					file, one per line.  Ignore any
+					IP addresses that are passed as
 					command-line arguments.
-		
-		-c,--country-only	Get country-level information 
+
+		-c,--country-only	Get country-level information
 					instead of city-level.  Faster.
-		
-		-k,--api-key		Specify a ipinfodb.com API key 
+
+		-k,--api-key		Specify a ipinfodb.com API key
 					to use when making API requests.
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 countryOnly=false
 filename=""
@@ -57,11 +57,11 @@ geolocateIp(){
 		else
 			loc=$(curl -s "http://api.ipinfodb.com/v3/ip-city/?key=$apiKey&ip=$ip" 2> /dev/null)
 		fi
-		
-		#Remove useless trailing information and prettyify the output a little
+
+		# Remove useless trailing information and prettyify the output a little
 		loc=$(echo "$loc" | sed 's/OK;;//')
 		loc=$(echo "$loc" | sed 's/;/\t/g')
-		
+
 		echo "$loc"
 	fi
 }
@@ -70,13 +70,13 @@ for i in "$@"
 do
 case $i in
 	-f=*|--file=*)
-		filename=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		filename=$(echo "$i" | sed 's/[-a-zA-Z0-9]*=//')
 	;;
 	-c|--country-only)
 		countryOnly=true
 	;;
 	-k=*|--api-key=*)
-		apiKey=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+		apiKey=$(echo "$i" | sed 's/[-a-zA-Z0-9]*=//')
 	;;
 esac
 done
@@ -92,15 +92,15 @@ if [ "$apiKey" = "" ]; then
 fi
 
 if [ "$filename" != "" ]; then
-	#We have input from a file
+	# We have input from a file
 	if [ -e "$filename" ]; then
-		for ip in `cat "$filename"`
+		for ip in $(cat "$filename")
 		do
 			ips=("${ips[@]}" "$ip")
 		done
 	fi
 else
-	#We have piped input
+	# We have piped input
 	if readlink /proc/$$/fd/0 | grep -q "^pipe:"; then
   		input=$(cat)
   		input=$(echo -e "$input" | sed 's/\s/\n/g')
@@ -109,14 +109,14 @@ else
 		done <<< "$input"
   	fi
 
-	#We have input from arguments
+	# We have input from arguments
 	for ip in $@
 	do
 		ips=("${ips[@]}" "${ip}")
 	done
 fi
 
-if [ ${#ips[@]} -gt 1 ]; then
+if [ ${# ips[@]} -gt 1 ]; then
 	pause="true"
 fi
 
diff --git a/kindle-sync b/kindle-sync
--- a/kindle-sync
+++ b/kindle-sync
@@ -4,26 +4,26 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Compile and sync ebooks in ~/documents/ebooks/ to an attached Kindle device, then eject it.  Epub files are compiled to mobi files and cover thumbnails are transferred automatically.
-	
+
 USAGE
 	kindle-sync [-d,--dry-run] [-c,--compile-only]
-	
-		-d,--dry-run		Simulate the sync and don't 
+
+		-d,--dry-run		Simulate the sync and don't
 					eject the device aftewards.
-		
-		-c,--compile-only	Compile only, don't sync to 
-					the device.  Can't be used 
+
+		-c,--compile-only	Compile only, don't sync to
+					the device.  Can't be used
 					with the -d option.
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
-ebooksRoot="$HOME/documents/ebooks/" #Trailing slash required
-kindleRoot="/media/Kindle" #No trailing slash please!
+ebooksRoot="$HOME/documents/ebooks/" # Trailing slash required
+kindleRoot="/media/Kindle" # No trailing slash please!
 
 require "rsync" "Try: apt-get install rsync"
 require "ebook-convert" "Try: apt-get install calibre"
@@ -31,34 +31,33 @@ require "ebook-extract"
 
 convertFile(){
 	md5=$(md5sum "$1" | awk '{ print $1 }')
-	tempPath="/tmp" #No trailing slash please!
 	filename=$(basename "$1" ".epub")
 	fileLocation=$(dirname "$1")
-	mobiPath="${fileLocation}"/"${filename}.compiled.mobi"
-	tempMobiPath="/tmp/mobi" #No trailing slash please!
-	
+	mobiPath="${fileLocation}/${filename}.compiled.mobi"
+	tempMobiPath="/tmp/mobi" # No trailing slash please!
+
 	echo "Compiling ${mobiPath} ..."
 
-	#First convert epub to mobi
+	# First convert epub to mobi
 	ebook-convert "$1" "${mobiPath}" > /dev/null 2>&1
-	
-	#Store the md5 sum of the epub
+
+	# Store the md5 sum of the epub
 	echo "${md5}" > "${fileLocation}/last-epub-md5"
 
-	#Extract the mobi file to get the asin
+	# Extract the mobi file to get the asin
 	rm -rf "${tempMobiPath}" > /dev/null 2>&1
-	ebook-extract -d="${tempMobiPath}" "${mobiPath}" 
+	ebook-extract -d="${tempMobiPath}" "${mobiPath}"
 
-	#Get the ASIN
+	# Get the ASIN
 	asin=$(grep -o -E '<meta name="ASIN" content="(.*)"' "${tempMobiPath}"/mobi7/*.opf | sed -E 's/.*content="(.*)"/\1/')
 
-	#Generate the thumbnail
+	# Generate the thumbnail
 	rm "${fileLocation}"/thumbnail_* > /dev/null 2>&1
-	
-	#Get the name of the cover image
+
+	# Get the name of the cover image
 	coverPath=$(grep -o -E '<item id="cover_img" media-type=".*?" href="(.*)"' "${tempMobiPath}"/mobi7/*.opf | sed -E 's/.*href\="(.*)"/\1/')
 
-	#Resize the cover
+	# Resize the cover
 	convert "${tempMobiPath}/mobi7/${coverPath}" -resize 216x330 "${fileLocation}/thumbnail_${asin}_EBOK_portrait.jpg" > /dev/null 2>&1
 }
 
@@ -66,10 +65,10 @@ dryRun=false
 compileOnly=false
 
 if [ $# -eq 1 ]; then
-	if [ "$1" = "--dry-run" -o "$1" = "-d" ]; then
+	if [ "$1" = "--dry-run" ] || [ "$1" = "-d" ]; then
 		dryRun="true"
 	fi
-	if [ "$1" = "--compile-only" -o "$1" = "-c" ]; then
+	if [ "$1" = "--compile-only" ] || [ "$1" = "-c" ]; then
 		compileOnly="true"
 	fi
 fi
@@ -82,52 +81,51 @@ fi
 
 find "${ebooksRoot}" -name "*.epub" | while read filePath;
 do
-	#Ignore epub files that end in .original.epub
+	# Ignore epub files that end in .original.epub
 	if [ "${filePath}" = *.original.epub ]; then
 		continue
 	fi
-	
-	#Ignore epub files that end in .wip.epub
+
+	# Ignore epub files that end in .wip.epub
 	if [ "${filePath}" = *.wip.epub ]; then
 		continue
 	fi
-	
-	#Do we have a cached copy of the mobi file?
-	fileName=$(basename "${filePath}" ".epub")
+
+	# Do we have a cached copy of the mobi file?
 	fileLocation=$(dirname "${filePath}")
-	
+
 	if ls "${fileLocation}/last-epub-md5" > /dev/null 2>&1 ; then
-		#Mobi exists
-		
+		# Mobi exists
+
 		currentMd5=$(md5sum "${filePath}" | awk '{ print $1 }')
 		cachedMd5=$(cat "${fileLocation}/last-epub-md5")
-		
-		#Have we made changes?
+
+		# Have we made changes?
 		if [ "${currentMd5}" != "${cachedMd5}" ]; then
 			convertFile "${filePath}"
 		fi
 	else
-		#Mobi does not exist, create it for the first time
+		# Mobi does not exist, create it for the first time
 		convertFile "${filePath}"
 	fi
 done
 
-#Rsync thumbnails to the device
+# Rsync thumbnails to the device
 rm -rf "/tmp/images-sync/" > /dev/null 2>&1
 mkdir -p "/tmp/images-sync/" > /dev/null 2>&1
 
-#Don't sync for a dry run
-if [ "${compileOnly}" != "true" -a "${dryRun}" != "true" ]; then
+# Don't sync for a dry run
+if [ "${compileOnly}" != "true" ] && [ "${dryRun}" != "true" ]; then
 	find "${ebooksRoot}" -name "*.jpg" | while read filePath;
 	do
 		cp "${filePath}" "/tmp/images-sync/"
 	done
-	
+
 	rsync -rlcvz --itemize-changes --include="*.jpg" --delete  "/tmp/images-sync/" "${kindleRoot}/system/thumbnails" > /dev/null 2>&1
 fi
 
-#Rsync books to the device
-#Ignore .sdr folders and .original.mobi files
+# Rsync books to the device
+# Ignore .sdr folders and .original.mobi files
 rm -rf "/tmp/mobi-sync" > /dev/null 2>&1
 
 if [ "${compileOnly}" != "true" ]; then
@@ -140,12 +138,12 @@ if [ "${dryRun}" = "true" ]; then
 	echo Starting rsync dry run ...
 	rsync -rlcvz --dry-run --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete  "${ebooksRoot}" "${kindleRoot}/documents/ebooks"
 elif [ "${compileOnly}" != "true" ]; then
-	#Empty my clippings
+	# Empty my clippings
 	echo "" > "${kindleRoot}/documents/My Clippings.txt"
 	rsync -rlcvz --itemize-changes --filter="P *.sdr" --include="*/" --exclude="*.original.mobi" --include="*.mobi" --exclude="*" --delete "${ebooksRoot}" "${kindleRoot}/documents/ebooks"
 fi
 
-if [ "${dryRun}" != "true" -a "${compileOnly}" != "true" ] ; then
+if [ "${dryRun}" != "true" ] && [ "${compileOnly}" != "true" ] ; then
 	echo "Ejecting Kindle ..."
 	sudo eject "${kindleRoot}"
 	echo "Done."
diff --git a/ogg-cover-art b/ogg-cover-art
--- a/ogg-cover-art
+++ b/ogg-cover-art
@@ -8,16 +8,16 @@ DESCRIPTION
 
 USAGE
 	ogg-cover-art [COVER-FILENAME] OGG-FILENAME
-		Add cover art to OGG-FILENAME.  If COVER-FILENAME is not specified, 
+		Add cover art to OGG-FILENAME.  If COVER-FILENAME is not specified,
 		use cover.jpg, cover.jpeg, or cover.png located in the same folder
 		as OGG-FILENAME.
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 require "vorbiscomment" "Try: apt-get install vorbis-tools"
 
@@ -58,71 +58,71 @@ fi
 
 imageMimeType=$(file -b --mime-type "${imagePath}")
 
-if [ "${imageMimeType}" != "image/jpeg" -a "${imageMimeType}" != "image/png" ]; then
+if [ "${imageMimeType}" != "image/jpeg" ] && [ "${imageMimeType}" != "image/png" ]; then
 	die "Cover image isn't a jpg or png image."
 fi
 
 oggMimeType=$(file -b --mime-type "${outputFile}")
 
-if [ "${oggMimeType}" != "audio/x-vorbis+ogg" -a "${oggMimeType}" != "audio/ogg" ]; then
+if [ "${oggMimeType}" != "audio/x-vorbis+ogg" ] && [ "${oggMimeType}" != "audio/ogg" ]; then
 	die "Input file isn't an ogg file."
 fi
 
-#Export existing comments to file
+# Export existing comments to file
 commentsPath="$(mktemp -t "tmp.XXXXXXXXXX")"
 vorbiscomment --list --raw "${outputFile}" > "${commentsPath}"
 
-#Remove existing images
+# Remove existing images
 sed -i -e '/^metadata_block_picture/d' "${commentsPath}"
 
-#Insert cover image from file
+# Insert cover image from file
 
-#metadata_block_picture format
-#See: https://xiph.org/flac/format.html#metadata_block_picture
+# metadata_block_picture format
+# See: https://xiph.org/flac/format.html# metadata_block_picture
 imageWithHeader="$(mktemp -t "tmp.XXXXXXXXXX")"
 description=""
 
-#Reset cache file
+# Reset cache file
 echo -n "" > "${imageWithHeader}"
 
-#Picture type <32>
+# Picture type <32>
 printf "0: %.8x" 3 | xxd -r -g0 >> "${imageWithHeader}"
 
-#Mime type length <32>
+# Mime type length <32>
 printf "0: %.8x" $(echo -n "${imageMimeType}" | wc -c) | xxd -r -g0 >> "${imageWithHeader}"
 
-#Mime type (n * 8)
+# Mime type (n * 8)
 echo -n "${imageMimeType}" >> "${imageWithHeader}"
 
-#Description length <32>
+# Description length <32>
 printf "0: %.8x" $(echo -n "${description}" | wc -c) | xxd -r -g0 >> "${imageWithHeader}"
 
-#Description (n * 8)
+# Description (n * 8)
 echo -n "${description}" >> "${imageWithHeader}"
 
-#Picture with <32>
+# Picture with <32>
 printf "0: %.8x" 0 | xxd -r -g0  >> "${imageWithHeader}"
 
-#Picture height <32>
+# Picture height <32>
 printf "0: %.8x" 0 | xxd -r -g0 >> "${imageWithHeader}"
 
-#Picture color depth <32>
+# Picture color depth <32>
 printf "0: %.8x" 0 | xxd -r -g0 >> "${imageWithHeader}"
 
-#Picture color count <32>
+# Picture color count <32>
 printf "0: %.8x" 0 | xxd -r -g0 >> "${imageWithHeader}"
 
-#Image file size <32>
+# Image file size <32>
 printf "0: %.8x" $(wc -c "${imagePath}" | cut --delimiter=' ' --fields=1) | xxd -r -g0 >> "${imageWithHeader}"
 
-#Image file
+# Image file
 cat "${imagePath}" >> "${imageWithHeader}"
 
 echo "metadata_block_picture=$(base64 --wrap=0 < "${imageWithHeader}")" >> "${commentsPath}"
 
-#Update vorbis file comments
+# Update vorbis file comments
 vorbiscomment --write --raw --commentfile "${commentsPath}" "${outputFile}"
 
-#Delete temp files
+# Delete temp files
 rm "${imageWithHeader}"
 rm "${commentsPath}"
diff --git a/pw b/pw
--- a/pw
+++ b/pw
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-passwordFilePath="${HOME}/.passwords" #No trailing slash
+passwordFilePath="${HOME}/.passwords" # No trailing slash
 clipboardTime=30
 configFile="${HOME}/.config/pw/private-key"
 syncFile="${HOME}/.config/pw/sync-credentials"
@@ -10,7 +10,7 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Create, edit, and view gpg-encrypted passwords stored in the ${passwordFilePath}/ folder.
-	
+
 	By default, pw encrypts passwords symmetrically using a passphrase.  To encrypt with a GPG key instead, create the file ~/.config/pw/private-key containing the email address of the private key to use.  The private key must be on your keychain.
 
 USAGE
@@ -19,7 +19,7 @@ USAGE
 
 	pw -g,--generate [DOMAIN]
 		Generate and print a new strong password to stdout and copy it to the clipboard for ${clipboardTime} seconds.  If invoked with a domain name, additionally prompt for a login, then store the login and generated password in the password store.
-	
+
 	pw -a,--add DOMAIN
 		Prompt for a login and password for a domain, then store those credentials in the password store.
 
@@ -28,19 +28,19 @@ USAGE
 
 	pw -e,--edit DOMAIN
 		Edit the information stored under that domain using a temporary file stored in a RAMFS mount.  Requires sudo privileges.
-	
+
 	pw -c,--sync [USER@HOST:DESTINATION]
 		Sync the ${passwordFilePath}/ folder to the USER@HOST:DESTINATION specified in ~/.config/pw/sync-credentials or as an argument.
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
-specialCharacters="01234567890!@#$%^&*(){}.,:;"
-tempMountPoint="/tmp/pw" #No trailing slash
+specialCharacters="01234567890!@# $%^&*(){}.,:;"
+tempMountPoint="/tmp/pw" # No trailing slash
 
 require "gpg" "Try: apt-get install gnupg"
 require "xclip" "Try: apt-get install xclip"
@@ -49,28 +49,28 @@ require "rsync" "Try: apt-get install rsync"
 
 generatePassword(){
 	password=$(sort -R /usr/share/dict/words | head -n 100 | grep -i '^[a-z]*$' | head -n 4 | sed ':a;N;$!ba;s/\n/ /g')
-		
-	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+
+	randomPos=$[ ( ${RANDOM} % ${# password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${# specialCharacters} )  +  1 ]-1:1}
 	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
-	
-	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+
+	randomPos=$[ ( ${RANDOM} % ${# password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${# specialCharacters} )  +  1 ]-1:1}
 	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
-	
-	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+
+	randomPos=$[ ( ${RANDOM} % ${# password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${# specialCharacters} )  +  1 ]-1:1}
 	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
-	
-	randomPos=$[ ( ${RANDOM} % ${#password} )  +  1 ]
-	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${#specialCharacters} )  +  1 ]-1:1}
+
+	randomPos=$[ ( ${RANDOM} % ${# password} )  +  1 ]
+	randomChar=${specialCharacters:$[ ( ${RANDOM} % ${# specialCharacters} )  +  1 ]-1:1}
 	password=$(echo "${password}" | sed "s/\(.\)/\1${randomChar}/${randomPos}")
-	
+
 	printf "%s" "${password}"
 }
 
 syncPasswords(){
-	#Remove any trailing slashes, then add one
+	# Remove any trailing slashes, then add one
 	target=${1%/}
 	target="${target}/"
 	rsync -acz --progress --itemize-changes --partial -e ssh "${passwordFilePath}/" "${target}"
@@ -80,20 +80,20 @@ if [ -f "${configFile}" ]; then
 	recipient=$(cat "${configFile}")
 fi
 
-if [ $# -eq 0 ]; then	
+if [ $# -eq 0 ]; then
 	tree "${passwordFilePath}/" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
 fi
 
 if [ $# -eq 1 ]; then
-	if [ "$1" = "-g" -o "$1" = "--generate" ]; then
+	if [ "$1" = "-g" ] || [ "$1" = "--generate" ]; then
 		password="$(generatePassword)"
-		
-		echo ${password}
+
+		echo "${password}"
 		printf "%s" "${password}" | xclip -selection clipboard
 		sleep "${clipboardTime}" && printf "" | xclip -selection clipboard &
-	elif [ "$1" = "-l" -o "$1" = "--list" ]; then
+	elif [ "$1" = "-l" ] || [ "$1" = "--list" ]; then
 		tree "${passwordFilePath}" | sed "s/\.gpg$//" | sed -n -e :a -e '1,2!{P;N;D;};N;ba'
-	elif [ "$1" = "-c" -o "$1" = "--sync" ]; then
+	elif [ "$1" = "-c" ] || [ "$1" = "--sync" ]; then
 		if [ -f "${syncFile}" ]; then
 			destination=$(cat "${syncFile}")
 			syncPasswords "${destination}"
@@ -104,7 +104,7 @@ if [ $# -eq 1 ]; then
 fi
 
 if [ $# -eq 2 ]; then
-	if [ "$1" = "-g" -o "$1" = "--generate" ]; then
+	if [ "$1" = "-g" ] || [ "$1" = "--generate" ]; then
 		if [ -f "${passwordFilePath}/$2.gpg" ]; then
 			printf "This domain already exists.  Overwrite? (y/n) "
 			read yn
@@ -114,23 +114,23 @@ if [ $# -eq 2 ]; then
 				* ) exit;;
 			esac
 		fi
-		
+
 		printf "Enter your login for this domain: "
 		read login
 
 		password="$(generatePassword)"
-		
+
 		if [ "${recipient}" = "" ]; then
 			printf "login: ${login}\npass: ${password}" | gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg"
 		else
 			printf "login: ${login}\npass: ${password}" | gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg"
 		fi
-	
+
 		printf "%s" "${password}"
 		printf "%s" "${password}" | xclip -selection clipboard
 		sleep "${clipboardTime}" && printf "" | xclip -selection clipboard &
-	elif [ "$1" = "-a" -o "$1" = "--add" ]; then
-		if [ -f "${passwordFilePath}/$2.gpg" ]; then	
+	elif [ "$1" = "-a" ] || [ "$1" = "--add" ]; then
+		if [ -f "${passwordFilePath}/$2.gpg" ]; then
 			printf "This domain already exists.  Overwrite? (y/n) "
 			read yn
 			case "${yn}" in
@@ -142,7 +142,7 @@ if [ $# -eq 2 ]; then
 
 		printf "Enter your login for this domain: "
 		read login
-		
+
 		printf "Enter your password for this domain: "
 		stty -echo
 		read password
@@ -152,28 +152,27 @@ if [ $# -eq 2 ]; then
 		read passwordConfirm
 		stty echo
 		printf "\n"
-		
+
 		if [ "${password}" != "${passwordConfirm}" ]; then
 			die "Passwords don't match."
 		fi
-		
+
 		if [ "${recipient}" = "" ]; then
 			printf "login: ${login}\npass: ${password}" | gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg"
 		else
 			printf "login: ${login}\npass: ${password}" | gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg"
 		fi
-	elif [ "$1" = "-s" -o "$1" = "--show" ]; then
+	elif [ "$1" = "-s" ] || [ "$1" = "--show" ]; then
 		if [ -f "${passwordFilePath}/$2.gpg" ]; then
 			text=$(gpg --use-agent --decrypt --no-tty "${passwordFilePath}/$2.gpg" 2> /dev/null)
-			
+
 			if [ $? -ne 0 ]; then
 				die "Invalid password."
 			fi
-			
+
 			printf "%s\n" "${text}"
-			
-			printf "%s" "${text}" | grep -i -E "^pass(word)?\:\s.*" > /dev/null 2>&1
-			if [ $? -eq 0 ]; then
+
+			if printf "%s" "${text}" | grep -i -E "^pass(word)?\:\s.*" > /dev/null 2>&1; then
 				password=$(printf "%s" "${text}" | grep -i -E "^pass(word)?\:\s.*" | sed -r "s/^pass(word)?\:\s//")
 				if [ "${password}" != "" ]; then
 					printf "%s" "${password}" | xclip -selection clipboard
@@ -183,49 +182,45 @@ if [ $# -eq 2 ]; then
 		else
 			die "File not found."
 		fi
-	elif [ "$1" = "-e" -o "$1" = "--edit" ]; then
+	elif [ "$1" = "-e" ] || [ "$1" = "--edit" ]; then
 		if [ -f "${passwordFilePath}/$2.gpg" ]; then
 			mkdir -p "${tempMountPoint}"
-			
+
 			sudo umount "${tempMountPoint}" > /dev/null 2>&1
-			
-			sudo mount -t ramfs -o size=20m ramfs "${tempMountPoint}"
-			
-			if [ $? -ne 0 ]; then
+
+			if ! sudo mount -t ramfs -o size=20m ramfs "${tempMountPoint}"; then
 				die "Couldn't create temporary mount.  Do you have sudo privileges?"
 			fi
-			
-			sudo chown $(whoami) "${tempMountPoint}"
-			
+
+			sudo chown "$(whoami)" "${tempMountPoint}"
+
 			filename="$(basename "$2")"
 			filePath="${tempMountPoint}/${filename}"
-			
-			gpg --use-agent --decrypt --no-tty --output "${filePath}" "${passwordFilePath}/$2.gpg" 2> /dev/null
-			
-			if [ $? -ne 0 ]; then
+
+			if ! gpg --use-agent --decrypt --no-tty --output "${filePath}" "${passwordFilePath}/$2.gpg" 2> /dev/null; then
 				sudo umount "${tempMountPoint}"
 				die "Invalid password."
 			fi
-			
+
 			if [ "${EDITOR}" = "" ]; then
 				vi "${filePath}"
 			else
 				"${EDITOR}" "${filePath}"
 			fi
-			
+
 			if [ "${recipient}" = "" ]; then
 				gpg --symmetric --armor --batch --yes --output "${passwordFilePath}/$2.gpg" "${filePath}"
 			else
 				gpg --encrypt --armor --batch --yes --recipient "${recipient}" --output "${passwordFilePath}/$2.gpg" "${filePath}"
 			fi
-			
+
 			rm "${filePath}"
-			
+
 			sudo umount "${tempMountPoint}"
 		else
 			die "File not found."
 		fi
-	elif [ "$1" = "-c" -o "$1" = "--sync" ]; then
+	elif [ "$1" = "-c" ] || [ "$1" = "--sync" ]; then
 		syncPasswords "$2"
 	fi
 fi
diff --git a/screen-toggle b/screen-toggle
--- a/screen-toggle
+++ b/screen-toggle
@@ -4,29 +4,28 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Toggle the laptop display on or off.
-	
+
 USAGE
 	screen-toggle
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 screenOffLockFile="/tmp/screen-toggle-lock/"
 
 if mkdir "${screenOffLockFile}"; then
 	while :
 	do
-		xset q | grep --quiet "Monitor is Off"
-		if [ $? -ne 0 ]; then
+		if ! xset q | grep --quiet "Monitor is Off"; then
 			if [ -d ${screenOffLockFile} ]; then
 				xset dpms force off
 			else
 				xset dpms force on
-				
+
 				exit
 			fi
 		fi
@@ -35,5 +34,4 @@ if mkdir "${screenOffLockFile}"; then
 else
 	rm -rf "${screenOffLockFile}"
 	xset dpms force on
-	#xbacklight -time 0 -set 100
 fi
diff --git a/socks-tunnel b/socks-tunnel
--- a/socks-tunnel
+++ b/socks-tunnel
@@ -4,28 +4,28 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Control a transparent system-level or browser-level SOCKS tunnel through a remote proxy.
-	
+
 	By default, socks-tunnel uses openvpn/badvpn-tun2socks to create a network-layer SOCKS tunnel to a remote proxy.  This transparently routes all traffic, including DNS, from the host through the proxy, on the network-layer level.
-	
+
 	With the --browser option, socks-tunnel instead creates a SOCKS tunnel to a remote proxy using SSH, then configures Firefox's proxy settings to use that tunnel.  This requires a Firefox restart.
-	
+
 USAGE
 	socks-tunnel -s,--start [-b,--browser] [-h,--host=USER@HOSTNAME]
 		If the -h option is ommitted, socks-tunnel looks in ~/.config/socks-tunnel/host for a USER@HOSTNAME string to connect to.
-	
+
 	socks-tunnel -x,--stop
-	
+
 	socks-tunnel -u,--status
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 localPort="12345"
-socksPort="11080" #The default socks port is 1080, but we use an alternate in case other services want to use that port
+socksPort="11080" # The default socks port is 1080, but we use an alternate in case other services want to use that port
 remoteConnection=""
 tempFilePath="/tmp/socks-tunnel"
 configFilePath="${HOME}/.config/socks-tunnel/host"
@@ -75,70 +75,67 @@ checkIfRunning(){
 }
 
 isFirefoxRunning(){
-	#Get the PID for the Firefox process
+	# Get the PID for the Firefox process
 	ffpid=$(ps ux | awk '/firefox/ && !/awk/ && !/socks/ {print $2}')
 	[ -n "${ffpid}" ]
 }
 
 startTun(){
-	#Save our detected settings
-	remoteUser=`echo "${remoteConnection}" | cut -d"@" -f1-1`
-	remoteHost=`echo "${remoteConnection}" | cut -d"@" -f2-2`
+	# Save our detected settings
+	remoteHost=$(echo "${remoteConnection}" | cut -d"@" -f2-2)
 	gatewayIp=$(/sbin/ip route | awk '/default/ { print $3 }')
 	remoteIp=$(host -t a "${remoteHost}" | awk '{print $4}')
 	printf "${gatewayIp}\n${remoteIp}" > "${tempFilePath}"
 
-	#Create the tun0 device
+	# Create the tun0 device
 	sudo openvpn --mktun --dev tun0 > /dev/null
-	
-	#Configure the tun0 device
-	sudo ifconfig tun0 10.0.0.1 netmask 255.255.255.0 > /dev/null
-	
-	#Enable the tun2socks program
-	badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:${socksPort} > /dev/null & 
-	disown %badvpn
-	
-	#Open our socks proxy
-	ssh -D localhost:${socksPort} -N -f ${remoteConnection}
 
-	#Connect to tun2socks instead of our default gateway (router)
-	sudo route add "${remoteIp}" gw "${gatewayIp}" metric 5 
-	sudo route add default gw 10.0.0.2 metric 6 #connect to tun2socks instead of our default gateway (router)
-	sudo route del default gw "${gatewayIp}" metric 0 #delete our default gateway connection
+	# Configure the tun0 device
+	sudo ifconfig tun0 10.0.0.1 netmask 255.255.255.0 > /dev/null
+
+	# Enable the tun2socks program
+	badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:${socksPort} > /dev/null &
+	disown %badvpn
+
+	# Open our socks proxy
+	ssh -D localhost:${socksPort} -N -f "${remoteConnection}"
+
+	# Connect to tun2socks instead of our default gateway (router)
+	sudo route add "${remoteIp}" gw "${gatewayIp}" metric 5
+	sudo route add default gw 10.0.0.2 metric 6 # connect to tun2socks instead of our default gateway (router)
+	sudo route del default gw "${gatewayIp}" metric 0 # delete our default gateway connection
 }
 
 stopTun(){
-	#Restore our detected settings
+	# Restore our detected settings
 	gatewayIp=$(awk "NR==1" "${tempFilePath}")
 	remoteIp=$(awk "NR==2" "${tempFilePath}")
-	
-	#Get the pid for the ssh and badvpn processes
+
+	# Get the pid for the ssh and badvpn processes
 	sshPid=$(ps ux | awk '/ssh -D/ && !/awk/ {print $2}')
 	badvpnPid=$(ps ux | awk '/badvpn/ && !/awk/ {print $2}')
 
-	#Remove our socks routes and restore our default gateway route
+	# Remove our socks routes and restore our default gateway route
 	sudo route del "${remoteIp}" gw "${gatewayIp}" metric 5 > /dev/null 2>&1
 	sudo route del default gw 10.0.0.2 metric 6 > /dev/null 2>&1
 	sudo route add default gw "${gatewayIp}" metric 0 > /dev/null 2>&1
-	
-	#Kill the ssh and badvpn processes
-	kill -HUP ${sshPid} > /dev/null 2>&1
-	kill -HUP ${badvpnPid} > /dev/null 2>&1
-	
-	#Remove the tun0 device
+
+	# Kill the ssh and badvpn processes
+	kill -HUP "${sshPid}" > /dev/null 2>&1
+	kill -HUP "${badvpnPid}" > /dev/null 2>&1
+
+	# Remove the tun0 device
 	sudo openvpn --rmtun --dev tun0 > /dev/null
-	
+
 	rm "${tempFilePath}"
 }
 
 startFirefox(){
-	ssh -D ${localPort} -N -f ${remoteConnection}
-
-	if [ $? -ne 0 ]; then
+	if ! ssh -D ${localPort} -N -f ${remoteConnection}; then
 		die "Could not establish SSH connection."
 	else
 		touch "${tempFilePath}"
-		
+
 		printf "user_pref(\"network.proxy.socks\", \"localhost\");\nuser_pref(\"network.proxy.socks_port\", ${localPort});\nuser_pref(\"network.proxy.socks_version\", 5);\nuser_pref(\"network.proxy.type\", 1);" > $(echo $(find ~/.mozilla/firefox -name '*.default')/user.js)
 
 		if isFirefoxRunning; then
@@ -151,19 +148,19 @@ stopFirefox(){
 	if isFirefoxRunning; then
 		die "Firefox is still running."
 	fi
-	
+
 	rm "${tempFilePath}"
-	
+
 	echo "user_pref(\"network.proxy.type\", 5);" > $(echo $(find ~/.mozilla/firefox -name '*.default')/user.js)
 
-	#Get the PID for the SSH process
+	# Get the PID for the SSH process
 	pid=$(ps ux | awk '/ssh -D/ && !/awk/ {print $2}')
 
 	if [ -z "${pid}" ]; then
 		die "Could not find SSH process ID."
 	else
 		kill -HUP "${pid}" > /dev/null 2>&1
-		
+
 		if isFirefoxRunning; then
 			echo "Restart Firefox to apply proxy changes."
 		fi
@@ -172,18 +169,18 @@ stopFirefox(){
 
 if [ "${command}" = "start" ]; then
 	checkIfRunning
-	
-	#If we haven't specified a host on the command line, try to find it in our config directory
+
+	# If we haven't specified a host on the command line, try to find it in our config directory
 	if [ "${remoteConnection}" = "" ]; then
 		if [ -f "${configFilePath}" ]; then
 			remoteConnection=$(cat "${configFilePath}")
 		fi
 	fi
-	
+
 	if [ "${remoteConnection}" = "" ]; then
 		error
 	fi
-	
+
 	if [ "${type}" = "tun" ]; then
 		startTun
 	elif [ "${type}" = "browser" ]; then
diff --git a/update-digital-ocean-dns-record b/update-digital-ocean-dns-record
--- a/update-digital-ocean-dns-record
+++ b/update-digital-ocean-dns-record
@@ -4,16 +4,16 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Check if the IP address of this host matches the DNS records of a remote host.  If it doesn't match, update the DNS records using the Digital Ocean API.
-	
+
 USAGE
 	update-digital-ocean-dns-record -d,--domain=DOMAIN -s,--subdomain=SUBDOMAIN -k,--api-key=DIGITALOCEANAPIKEY
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 require "curl" "Try: apt-get install curl"
 require "jq" "Try: apt-get install jq"
@@ -37,18 +37,18 @@ case "${i}" in
 esac
 done
 
-if [ "${apiKey}" = "" -o "${domain}" = "" -o "${subdomain}" = "" ]; then
+if [ "${apiKey}" = "" ] || [ "${domain}" = "" ] || [ "${subdomain}" = "" ]; then
 	usage
 fi
 
-#look up the existing dns entry
+# look up the existing dns entry
 dnsIp=$(dig +short "${domain}")
 
 if [ "${dnsIp}" = "" ]; then
 	die "Couldn't resolve ${domain} while looking up DNS records."
 fi
 
-#look up our external ip
+# look up our external ip
 localIp=$(curl ifconfig.me 2> /dev/null)
 
 if [ $? -ne 0 ]; then
@@ -56,13 +56,13 @@ if [ $? -ne 0 ]; then
 fi
 
 if [ "${dnsIp}" != "${localIp}" ]; then
-	#Get the record ID from Digital Ocean
+	# Get the record ID from Digital Ocean
 	subdomainId=$(curl --silent --request GET --header "Content-Type: application/json" --header "Authorization: Bearer ${apiKey}" "https://api.digitalocean.com/v2/domains/${domain}/records" | jq ".[] | . [] | select(.name==\"${subdomain}\")" 2>/dev/null | grep "id" | sed --regexp-extended "s/[^0-9]//g")
-	
+
 	if [ $? -ne 0 ]; then
 		die "Couldn't get subdomain ID from Digital Ocean."
 	fi
-	
+
 	curl --silent --request PUT --header "Content-Type: application/json" --header "Authorization: Bearer ${apiKey}" -d "{\"data\":\"${localIp}\"}" "https://api.digitalocean.com/v2/domains/${domain}/records/${subdomainId}" > /dev/null
 
 	if [ $? -ne 0 ]; then
diff --git a/update-linode-dns-record b/update-linode-dns-record
--- a/update-linode-dns-record
+++ b/update-linode-dns-record
@@ -4,16 +4,16 @@ usage(){
 	fmt <<EOF
 DESCRIPTION
 	Check if the IP address of this host matches the DNS records of a remote host.  If it doesn't match, update the DNS records using the Linode API.
-	
+
 USAGE
 	update-dns-record -h,--host=HOSTNAME -k,--api-key=LINODEAPIKEY -d,--domain-id=LINODEDOMAINID -r,--resource-id=LINODERESOURCEID
 EOF
 	exit
 }
-die(){ printf "Error: ${1}\n" 1>&2; exit 1; }
-require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
-#End boilerplate
+die(){ printf "Error: %s\n" "${1}" 1>&2; exit 1; }
+require(){ command -v "${1}" > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
+if [ $# -eq 1 ]; then if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then usage; fi fi
+# End boilerplate
 
 require "curl" "Try: apt-get install curl"
 
@@ -40,18 +40,18 @@ case "${i}" in
 esac
 done
 
-if [ "${dynamicHost}" = "" -o "${linodeApiKey}" = "" -o "${domainId}" = "" -o "${resourceId}" = "" ]; then
+if [ "${dynamicHost}" = "" ] || [ "${linodeApiKey}" = "" ] || [ "${domainId}" = "" ] | [ "${resourceId}" = "" ]; then
 	usage
 fi
 
-#look up the existing dns entry
+# look up the existing dns entry
 dnsIp=$(dig +short "${dynamicHost}")
 
 if [ "${dnsIp}" = "" ]; then
 	die "Could not resolve ${dynamicHost} while looking up DNS records."
 fi
 
-#look up our external ip
+# look up our external ip
 localIp=$(curl ifconfig.me 2> /dev/null)
 
 if [ $? -ne 0 ]; then
@@ -60,7 +60,7 @@ fi
 
 if [ "${dnsIp}" != "${localIp}" ]; then
 	curl "https://api.linode.com/?api_key=${linodeApiKey}&api_action=domain.resource.update&domainid=${domainId}&resourceid=${resourceId}&target=${localIp}" > /dev/null 2>&1
-	
+
 	if [ $? -ne 0 ]; then
 		die "Could not connect to Linode API."
 	fi
